### ISSUE TITLE
ImportError: No module named 'bloch.bloch_simulator'

### ISSUE THREAD

**Issue by kingaza** [neji49/bloch-simulator-python#2]
After compiling and installing successfully, I try it by 'python BlochTest.py', unfortunately, there is an error that
ImportError: No module named 'bloch.bloch_simulator'
I am not sure what the wrong is. This error happens in python3.4 on both my Win7 and Mac.

**Comment by kingaza** [comment]
well, stupid problem..

**Comment by ateeple** [comment]
Just for fellow people having the same problem, how did you fix it?

**Comment by namalkanti** [comment]
@ateeple This problem is a Python import error and the solution will differ based on your env. At a high level, the module isn't installed correctly or in your PYTHON_PATH; but there a lot of reasons for this.
